### PR TITLE
Xdmf parallel print

### PR DESCRIPTION
**Pull request by giorgiobornia**

### CODE REVIEW

**Comment by eaulisa** [comment]
FSI still does not print correctly. Moreover, since we want to localize to iproc = 0 only, then it is better to use localize_to_one becuase this create a std::vec only on iproc = 0. Instead localize create a serial numeric vector on all the procs. Resulting in more time in communication and more memory allocation.

**Comment by giorgiobornia** [comment]
which one does not print correctly? turek_2d_FSI prints correctly in parallel in my computer.

**Comment by eaulisa** [comment]
mpirun -n 4 fsisteady turek_2D_FSI

**Comment by giorgiobornia** [comment]
In my computer I can see all fields correctly printed. I also added Domain_partitions. I don't know... have you merged the latest master tip?

**Comment by eaulisa** [comment]
yes

**Comment by eaulisa** [comment]
I will try it again...

**Comment by eaulisa** [comment]
did you change the format in the main to xdmf?

**Comment by eaulisa** [comment]
no doesn't work on mine paraview 4.3.1

**Comment by giorgiobornia** [comment]
i have paraview 3.98, probably that is the reason. Does it go in segfault? Now I have to go.

**Comment by eaulisa** [comment]
no just print ugly

**Comment by eaulisa** [comment]
ok. if you send me your files in an email and I will try to open them.

**Comment by giorgiobornia** [comment]
Now I use paraview 4.3.1 and I can see the files that I sent you correctly.

**Comment by eaulisa** [comment]
I can see yours but the ones that I print are unredable ...
Do you use hdf5 from petsc or installed by yourself?

**Comment by eaulisa** [comment]
OK I restarted all my system and now I can see it.
The only thing is that the field U is wrong, but V and P are correct.
I am going to check why.
I am also changing localize to localize to one

**Comment by eaulisa** [comment]
the truth is that is very unstable
sometimes it prints a right solution, sometimes no. I believe there is a problem in the binary writing

**Comment by eaulisa** [comment]
in debug mode seams to works, but no in release
found a valgrind error and fixed but didn't fix the problem

**Comment by eaulisa** [comment]
yes, it is debug vs release in my computer

**Comment by eaulisa** [comment]
or no, the randomness is strange ....

**Comment by eaulisa** [comment]
secondo Simone quest'errore nella stampa parallela xdmf c'e' semprestato ...

**Comment by giorgiobornia** [comment]
I don't know, I always print in parallel. I will look into that more closely.

**Comment by eaulisa** [comment]
is this a parallel print or just a scalar print from iproc 0? If is just a scalar print from iproc  0 once the data have been passed to him it should not be a problem. it is just as the scala case.

**Comment by giorgiobornia** [comment]
you send everything to zero and then print.
Usually i have the whole routine wrapped around an if (proc == 0),
and i localize the proc 0 before this if.

Maybe the reason is that.


--
Giorgio Bornia, Ph.D.
Assistant Professor
Department of Mathematics and Statistics
Texas Tech University
79409-1042 Lubbock, TX
phone: +1 (806) 834-8754
fax:     +1 (806) 742-1112
website: http://www.math.ttu.edu/~gbornia
________________________________

**Comment by eaulisa** [comment]
OK I think I fixed it! do you want me to push it? or you are working on it?

**Comment by giorgiobornia** [comment]
Good, you can push it.

**Comment by eaulisa** [comment]
done

**Pull request merged**
